/*--------------------Sequences----------------------------------*/

CREATE SEQUENCE AddressID_seq
START WITH 1
MAXVALUE
5000
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE EventID_seq
START WITH 1
MAXVALUE
5000
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE PalletID_seq
START WITH 1
MAXVALUE
5000
INCREMENT BY 1
NOCYCLE;